### ISSUE TITLE
"This app can't run on your PC" | Can't install StandSupportTool

### ISSUE THREAD

**Issue by yellowdude040212** [AXOca/StandSupportTool#11] opened 2024-10-09 01:48 UTC
How to fix this ?

I cannot use StandSupportTool without installing "windowsdesktop-runtime"

But when I try to install it, it says my PC cannot run it.

![image](https://github.com/user-attachments/assets/cc80cb71-3655-4f4b-891c-458071d7ef93)

**Comment by alessandromrc** [comment] 2024-11-09 01:23
Dupe of #10

**Closed as completed by alessandromrc** 2024-11-09 01:23 UTC
